@token = <<JWT_TOKEN_HERE>>

POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test_password"
}
###

POST http://localhost:3000/users/signin
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test_password"
}
###

GET http://localhost:3000/events
Content-Type: application/json

###

POST http://localhost:3000/events
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----RestClientFormBoundary

------RestClientFormBoundary
Content-Disposition: form-data; name="name"

Test Event
------RestClientFormBoundary
Content-Disposition: form-data; name="date"

2026-03-23
------RestClientFormBoundary
Content-Disposition: form-data; name="description"

Test Description
------RestClientFormBoundary
Content-Disposition: form-data; name="image"; filename="bookclub.png"
Content-Type: image/png

< <<Path/To/Image>>/bookclub.png
------RestClientFormBoundary--
###

PUT http://localhost:3000/events/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "April Book Club",
  "date": "2026-04-23",
  "description": "First meeting in Chapel Allerton"
}
###

DELETE http://localhost:3000/events/1
Authorization: Bearer {{token}}
Content-Type: application/json
###

POST http://localhost:3000/events/1/register
Authorization: Bearer {{token}}
Content-Type: application/json
###

DELETE http://localhost:3000/events/1/unregister
Authorization: Bearer {{token}}
Content-Type: application/json
###